### ISSUE TITLE
Adding US Identification Numbers to the User model

### ISSUE THREAD

**Issue by AlfG71** [Dia-Dev-Design/grassroots-nexus-server#4]
We need to add a US Voter Registration number, a US Driver's License number, and a US Passport Number as properties to our User Model.

**User model:**
- US Voter registration number
- US License number
- US Passport number

**Task Requirements:**

- Implement these properties to the `User` model using Mongoose schema definitions.

**Comment by alextor2625** [comment]
Hey Alfonso. Brennen and I completed the issue. Apparently Licence Number and Voter Registration was already in the user Schema. So what we did was add Passport number, and set email and password as required as an extra layer of protection to the database. We started the merge with main and awaiting for revision.

**Comment by AlfG71** [comment]
Thank you!

Please review the comment on the pull request #6

**Comment by alextor2625** [comment]
Alfonso I pushed a new version of this branch. Basically I modified the User Schema so that it has a few sub schemas to manage identification and address so that they are both stored in an object format. I included the address in this change since we wanted both the identification and address to be stored as an object format I thought I might as well do include it in the change. Here is an example of how a document would look like:

{ "_id": ..., "fullName": "John Doe", "email": "john@example.com", "password": "hashedpassword", "userName": "johndoe", "phoneNumber": "123456789", "address": { "street": "123 Main St", "city": "Anytown", "state": "CA", "zip": "12345" }, "identification": { "identificationType": "US Passport", "identificationNumber": "123456789" }, "volunteer": true, "donations": [], "eventsAttended": [], "createdAt": ..., "updatedAt": ... }

I would appreciate any feedback you have on this. Thanks.
